# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KafkaBuffer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('topic', models.CharField(max_length=100)),
                ('partition', models.IntegerField(default=0)),
                ('data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'kafka_buffer',
            },
        ),
        migrations.CreateModel(
            name='KafkaConsumerOffset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('partition', models.IntegerField(default=0)),
                ('offset', models.BigIntegerField()),
            ],
            options={
                'db_table': 'kafka_offset',
            },
        ),
        migrations.AlterUniqueTogether(
            name='kafkaconsumeroffset',
            unique_together=set([('topic', 'partition')]),
        ),
        migrations.AlterIndexTogether(
            name='kafkabuffer',
            index_together=set([('is_sent', 'id'), ('is_sent', 'created_at')]),
        ),
    ]
